#pragma once

enum RENGINE_POLYGON_TYPE
{
	RENGINE_POLYGON_TYPE_POINTS,
	RENGINE_POLYGON_TYPE_LINES,
	RENGINE_POLYGON_TYPE_LINE_LOOP,
	RENGINE_POLYGON_TYPE_LINE_STRIP,
	RENGINE_POLYGON_TYPE_TRIANGLES,
	RENGINE_POLYGON_TYPE_TRIANGLE_STRIP,
	RENGINE_POLYGON_TYPE_TRIANGLE_FAN,
	RENGINE_POLYGON_TYPE_QUADS,
	RENGINE_POLYGON_TYPE_QUAD_STRIP
};

enum RENGINE_INDEX_TYPE
{
	RENGINE_INDEX_TYPE_BYTE,
	RENGINE_INDEX_TYPE_UNSIGNED_BYTE,
	RENGINE_INDEX_TYPE_SHORT,
	RENGINE_INDEX_TYPE_UNSIGNED_SHORT,
	RENGINE_INDEX_TYPE_INT,
	RENGINE_INDEX_TYPE_UNSIGNED_INT,
	RENGINE_INDEX_TYPE_FLOAT,
};

enum RENGINE_RENDER_MODE
{
	DISABLED,
	SOLID,
	WIREFRAME,
	SOLIDWIREFRAME,
	OPACITY,
	ADD,
	UI
};

enum RENGINE_PIXEL_FORMAT
{
	RENGINE_PIXEL_FORMAT_RGB,
	RENGINE_PIXEL_FORMAT_RGBA,
	RENGINE_PIXEL_FORMAT_RGB16F,
	RENGINE_PIXEL_FORMAT_RGB32F,
	RENGINE_PIXEL_FORMAT_RGBA16F,
	RENGINE_PIXEL_FORMAT_RGBA32F
};

enum RENGINE_PIXEL_TYPE
{
	RENGINE_PIXEL_TYPE_UNSIGNED_BYTE,
	RENGINE_PIXEL_TYPE_FLOAT
};